In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import matplotlib.pyplot as plt
from PIL import Image
import re
import matplotlib.patches as patches
#from ultralytics import YOLO
import os
import yaml

In [2]:
train = pd.read_csv("Data/Test.csv")
test = pd.read_csv("Data/Test.csv")

train.head()

          image_id
0  id_uawi0k5spci5
1  id_ba566jv4xzln
2  id_q4odggcgnc77
3  id_4lrqmvmmgier
4  id_sqadni8gqzao